"""VPN commands plus the namespace-scoped shell."""

from __future__ import annotations

import os
from pathlib import Path

from .. import api, config, hosts, proxy, ui, vpn
from . import common

RCFILE_BASH = """# generated by htb-cli
if [ -f /etc/bash.bashrc ]; then . /etc/bash.bashrc; fi
if [ -f "$HOME/.bashrc" ]; then . "$HOME/.bashrc"; fi
PS1="\\[\\e[38;5;205m\\]\u2b22 htb\\[\\e[0m\\]${HTB_MACHINE:+ \\[\\e[36m\\]$HTB_MACHINE\\[\\e[0m\\]} $PS1"
alias target='echo $HTB_TARGET'
"""

RCFILE_ZSH = """# generated by htb-cli
[ -f "$HOME/.zshrc" ] && source "$HOME/.zshrc"
PROMPT="%F{205}\u2b22 htb%f${HTB_MACHINE:+ %F{cyan}$HTB_MACHINE%f} $PROMPT"
alias target='echo $HTB_TARGET'
"""


# --- vpn --------------------------------------------------------------------

def vpn_up(args):
    product = common.vpn_product(args)
    client = None if product in vpn.LOCAL_PRODUCTS else common.client(args)
    meta = vpn.up(
        client,
        ns=common.ns_for(args),
        product=product,
        tcp=args.tcp or config.get("vpn_protocol") == "tcp",
        internet=not args.no_internet and config.get("netns_internet"),
        veth=not args.no_veth and config.get("netns_veth"),
        mode=common.vpn_mode(args),
        reuse=not args.force,
    )

    def render():
        ui.success(f"Connected to {ui.c(meta['name'], 'bold')} ({meta['product']})")
        scope = ("only inside namespace " + ui.c(meta["ns"], "bold")
                 if meta["mode"] == "netns" else ui.c("system-wide", "yellow"))
        ui.kv([("tun ip", ui.c(meta.get("ip"), "cyan")),
               ("scope", scope),
               ("internet", "via NAT" if meta.get("internet") else "lab only"),
               ("log", str(vpn.paths(meta["ns"])["log"]))], indent=2)
        if meta["mode"] == "netns":
            ui.info(f"Open a connected shell with {ui.c('htb shell', 'bold')}")
    ui.emit(meta, render)
    started = proxy.maybe_up(args, meta)
    if started:
        meta["proxy"] = started


def vpn_down(args):
    ns = common.ns_for(args)
    if not vpn.is_up(ns, common.vpn_mode(args)) and not vpn.netns_exists(ns):
        ui.info("VPN is not running.")
        if not args.force:
            return
    if common.vpn_mode(args) != "netns":
        hosts.clear()  # the namespace hosts file goes away with the namespace
    vpn.down(ns)


def vpn_status(args):
    ns = common.ns_for(args)
    mode = common.vpn_mode(args)
    up = vpn.is_up(ns, mode)
    meta = vpn.read_meta(ns)
    remote = []
    if config.get_token():
        try:
            remote = common.client(args).connection_status()
        except (api.ApiError, SystemExit):
            pass

    proxy_state = proxy.status(ns) if mode == "netns" else {"running": False}
    payload = {"local": {"up": up, "ns": ns, "mode": mode, **meta},
               "proxy": proxy_state, "htb": remote}

    def render():
        ui.kv([
            ("state", ui.c("connected", "green") if up else ui.c("down", "grey")),
            ("scope", f"namespace {ns}" if mode == "netns" else "system-wide"),
            ("server", meta.get("name")),
            ("product", meta.get("product")),
            ("protocol", meta.get("protocol")),
            ("tun ip", vpn.tun_ip(ns)),
            ("pid", vpn.pid_of(ns)),
            ("internet", ("via NAT" if meta.get("internet") else "lab only") if up else None),
        ])
        if proxy_state.get("running"):
            print()
            ui.rule("lab proxy")
            ui.kv([
                ("endpoint", ui.c(f"{proxy_state['host']}:{proxy_state['port']}", "bold")),
                ("protocols", "socks5, http connect"),
                ("reachable", ui.c("yes", "green") if proxy_state["reachable"]
                 else ui.c("not answering", "red")),
                ("localhost", f"127.0.0.1:{proxy_state['port']}"
                 if proxy_state.get("localhost") else None),
                ("auth", "required" if proxy_state.get("auth") else "open (host-only link)"),
                ("pid", proxy_state.get("pid")),
            ])
        if remote:
            print()
            ui.rule("htb sees")
            for conn in remote:
                server = conn.get("server") or {}
                connection = conn.get("connection") or {}
                ui.kv([(conn.get("type", "connection"),
                        f"{server.get('friendly_name', '?')}  "
                        f"{connection.get('ip4') or connection.get('ip') or ''}")])
        addresses = vpn.ns_report(ns) if mode == "netns" and up else ""
        if addresses:
            print()
            ui.rule("namespace interfaces")
            print(addresses)
    ui.emit(payload, render)


def _api_product(args) -> str:
    product = args.product or config.get("vpn_product")
    if product in vpn.LOCAL_PRODUCTS:
        ui.die(f"{product} VPN servers are managed on the website ({vpn.ACADEMY_VPN_URL}); "
               "download a config there and import it with `htb vpn up --academy --ovpn <file>`.")
    return product


def vpn_servers(args):
    product = _api_product(args)
    client = common.client(args)
    servers = vpn.list_servers(client, product)
    rows = [[
        ui.c(s["id"], "grey"),
        ui.c(s["name"], "bold") + (ui.c("  ← assigned", "green") if s.get("assigned") else ""),
        s.get("location") or "",
        s.get("clients") if s.get("clients") is not None else "",
    ] for s in servers]
    ui.emit(servers, lambda: ui.table(["ID", "SERVER", "LOCATION", "CLIENTS"], rows,
                                      aligns=["r", "l", "l", "r"]))


def vpn_switch(args):
    product = _api_product(args)
    client = common.client(args)
    servers = vpn.list_servers(client, product)
    if args.server.isdigit():
        target = next((s for s in servers if str(s["id"]) == args.server),
                      {"id": int(args.server), "name": args.server})
    else:
        matches = [s for s in servers if args.server.lower() in (s["name"] or "").lower()]
        target = ui.choose("Matching servers:", matches,
                           lambda s: f"{s['name']}  ({s.get('location')})",
                           assume_yes=args.yes)
        if not target:
            ui.die(f"No VPN server matches {args.server!r}.")
    response = client.vpn_switch(target["id"])
    ui.emit(response, lambda: ui.success(
        api.message_of(response, f"Switched to {target['name']}.")))


def vpn_config(args):
    product = _api_product(args)
    client = common.client(args)
    dest = Path(args.output).expanduser() if args.output else Path.cwd() / f"htb-{product}.ovpn"
    meta = vpn.download_config(client, product, args.tcp, dest)
    ui.emit(meta, lambda: ui.success(f"Saved {meta['name']} config to {dest}"))


# --- proxy ------------------------------------------------------------------

def proxy_up(args):
    ns = common.ns_for(args)
    if common.vpn_mode(args) == "global":
        ui.die("A system-wide VPN needs no proxy - the host already routes to the lab.")
    if not vpn.is_up(ns, "netns"):
        ui.die("VPN namespace is not up. Run `htb vpn up` first.")
    meta = proxy.up(ns, port=args.port, listen=args.listen, auth=args.proxy_auth,
                    localhost=args.proxy_localhost, quiet=ui.JSON_MODE)
    if not meta:
        raise SystemExit(1)
    ui.emit(meta, lambda: None)


def proxy_down(args):
    proxy.down(common.ns_for(args))


def proxy_status(args):
    ns = common.ns_for(args)
    state = proxy.status(ns)

    def render():
        if not state["running"]:
            ui.info("Lab proxy is not running.")
            return
        ui.kv([
            ("endpoint", ui.c(f"{state['host']}:{state['port']}", "bold")),
            ("bound to", f"{state['listen']} inside namespace {ns}"),
            ("protocols", "socks5, http connect, http absolute-url"),
            ("reachable", ui.c("yes", "green") if state["reachable"]
             else ui.c("not answering", "red")),
            ("localhost", f"127.0.0.1:{state['port']}" if state["localhost"] else "no"),
            ("auth", "required" if state["auth"] else "open (host-only link)"),
            ("pid", state["pid"]),
            ("log", state["log"]),
        ])
    ui.emit(state, render)


def proxy_url(args):
    """Print the proxy URL for scripts: export ALL_PROXY=$(htb proxy url)."""
    value = proxy.url(common.ns_for(args), scheme=args.scheme)
    if not value:
        ui.die("Lab proxy is not running.")
    print(value)


# --- shell ------------------------------------------------------------------

def _shell_argv(ns: str) -> tuple:
    shell = config.get("shell") or os.environ.get("SHELL") or "/bin/bash"
    name = Path(shell).name
    rc_dir = config.CACHE_DIR / "shell"
    rc_dir.mkdir(parents=True, exist_ok=True)
    if name == "bash":
        rc = rc_dir / "bashrc"
        rc.write_text(RCFILE_BASH)
        return [shell, "--rcfile", str(rc), "-i"], {}
    if name == "zsh":
        zdot = rc_dir / "zsh"
        zdot.mkdir(exist_ok=True)
        (zdot / ".zshrc").write_text(RCFILE_ZSH)
        return [shell, "-i"], {"ZDOTDIR": str(zdot)}
    return [shell], {}


def enter_shell(args, profile=None, ip=None) -> int:
    """Replace the current process with a shell inside the namespace."""
    ns = common.ns_for(args)
    if common.vpn_mode(args) == "global":
        ui.die("`--global` connects the whole machine; just use your normal shell.")
    if not vpn.is_up(ns, "netns"):
        ui.die("VPN namespace is not up. Run `htb vpn up` (or `htb start <machine>`).")

    argv, extra_env = _shell_argv(ns)
    env = common.target_env(profile or {}, ip or "", ns)
    env.update(extra_env)

    name = (profile or {}).get("name")
    print()
    ui.rule("htb shell")
    ui.kv([
        ("namespace", ui.c(ns, "bold")),
        ("target", ui.c(ip, "cyan", "bold") if ip else ui.c("none running", "grey")),
        ("machine", name),
        ("hostname", f"{name.lower()}.htb" if name else None),
        ("note", "only this shell is on the HTB network - exit to leave"),
    ], indent=2)
    print()
    return vpn.exec_in_ns(ns, argv, env)


def shell(args):
    if common.academy(args):
        if args.machine:
            ui.die("Academy targets are spawned on academy.hackthebox.com; "
                   "drop the machine name.")
        if not args.no_vpn:
            common.ensure_vpn(args, None, product=common.vpn_product(args))
        raise SystemExit(enter_shell(args, None, getattr(args, "target", None)))

    client = common.client(args)
    if args.machine:
        from . import machine as machine_cmd
        args.shell = True
        machine_cmd.start(args)
        return

    profile, ip = None, None
    try:
        active = client.machine_active()
    except api.ApiError:
        active = None
    if active and active.get("id"):
        profile = client.machine_profile(active["id"])
        ip = active.get("ip") or profile.get("ip")

    product = "labs"
    if profile:
        product = "starting_point" if profile.get("sp_flag") else "labs"
    common.ensure_vpn(args, client, product=product)
    if profile:
        common.ensure_vpn_server(args, client, (active or {}).get("vpn_server_id"),
                                 product=product)

    ns = common.ns_for(args)
    if ip and profile and config.get("manage_hosts"):
        hosts.update(ip, profile["name"], ns=ns)
    raise SystemExit(enter_shell(args, profile, ip))


def exec_cmd(args):
    """Run a single command inside the namespace."""
    ns = common.ns_for(args)
    if args.command and args.command[0] == "--":
        args.command = args.command[1:]
    if not args.command:
        ui.die("Nothing to run: `htb exec -- nmap -sV $HTB_TARGET`")
    if not vpn.is_up(ns, "netns"):
        ui.die("VPN namespace is not up. Run `htb vpn up` first.")
    env = {"HTB_NETNS": ns, "TERM": os.environ.get("TERM", "xterm-256color")}
    # On the Academy VPN the labs' running machine is not reachable, so do
    # not advertise it as the target.
    try:
        on_labs = vpn.read_meta(ns).get("product") not in vpn.LOCAL_PRODUCTS
        active = common.client(args).machine_active() if on_labs else None
        if active:
            env.update({"HTB_TARGET": active.get("ip") or "",
                        "HTB_MACHINE": active.get("name") or ""})
    except (api.ApiError, SystemExit):
        pass
    env = {k: v for k, v in env.items() if v}
    command = [arg.replace("$HTB_TARGET", env.get("HTB_TARGET", "")) if "$HTB_TARGET" in arg
               else arg for arg in args.command]
    raise SystemExit(vpn.exec_in_ns(ns, command, env))
